### ISSUE TITLE
About Table2 in paper

### ISSUE THREAD

**Issue by House-Leo** [greatlog/DAN#14]
In Class 2 Line 4 PSNR 25.43 SSIM 0.6907
But when I use RealSR[https://github.com/Tencent/Real-SR](url) pre-model DF2K.pth to test DIV2KRK, get the result PSNR 28.044 SSIM 0.779
![image](https://user-images.githubusercontent.com/47940711/101728233-03c98580-3af1-11eb-80ef-b858869776cf.png)

**Comment by greatlog** [comment]
I test the images of DIV2KRK using the official codes. The PSNR results are then calculated by codes provided in mmsr. The log file is shown below. 

```bash
name: 1.png  PSNR: 25.1982 SSIM: 0.649866
name: 10.png  PSNR: 25.9101 SSIM: 0.693702
name: 100.png  PSNR: 21.4348 SSIM: 0.622757
name: 11.png  PSNR: 25.6796 SSIM: 0.608156
name: 12.png  PSNR: 25.9424 SSIM: 0.725101
name: 13.png  PSNR: 25.7398 SSIM: 0.762747
name: 14.png  PSNR: 25.7414 SSIM: 0.827590
name: 15.png  PSNR: 31.2067 SSIM: 0.878845
name: 16.png  PSNR: 28.4497 SSIM: 0.746119
name: 17.png  PSNR: 28.4146 SSIM: 0.802731
name: 18.png  PSNR: 25.2095 SSIM: 0.787351
name: 19.png  PSNR: 24.7117 SSIM: 0.613959
name: 2.png  PSNR: 29.4142 SSIM: 0.822745
name: 20.png  PSNR: 20.7445 SSIM: 0.580091
name: 21.png  PSNR: 20.9119 SSIM: 0.677046
name: 22.png  PSNR: 26.4613 SSIM: 0.706185
name: 23.png  PSNR: 24.3018 SSIM: 0.721123
name: 24.png  PSNR: 24.2259 SSIM: 0.781531
name: 25.png  PSNR: 22.4599 SSIM: 0.599798
name: 26.png  PSNR: 22.5480 SSIM: 0.625456
name: 27.png  PSNR: 29.0917 SSIM: 0.822089
name: 28.png  PSNR: 16.3657 SSIM: 0.600568
name: 29.png  PSNR: 25.8496 SSIM: 0.500479
name: 3.png  PSNR: 30.0753 SSIM: 0.916393
name: 30.png  PSNR: 23.5194 SSIM: 0.616623
name: 31.png  PSNR: 24.1232 SSIM: 0.679874
name: 32.png  PSNR: 24.5258 SSIM: 0.711132
name: 33.png  PSNR: 29.4762 SSIM: 0.873481
name: 34.png  PSNR: 24.1261 SSIM: 0.669190
name: 35.png  PSNR: 22.2962 SSIM: 0.426076
name: 36.png  PSNR: 22.4708 SSIM: 0.641565
name: 37.png  PSNR: 22.4536 SSIM: 0.612771
name: 38.png  PSNR: 34.4451 SSIM: 0.890101
name: 39.png  PSNR: 28.3216 SSIM: 0.765556
name: 4.png  PSNR: 23.8126 SSIM: 0.608969
name: 40.png  PSNR: 25.6396 SSIM: 0.665037
name: 41.png  PSNR: 26.3366 SSIM: 0.769627
name: 42.png  PSNR: 26.6107 SSIM: 0.750407
name: 43.png  PSNR: 33.0029 SSIM: 0.962516
name: 44.png  PSNR: 34.7669 SSIM: 0.975681
name: 45.png  PSNR: 21.0279 SSIM: 0.586573
name: 46.png  PSNR: 24.6369 SSIM: 0.764714
name: 47.png  PSNR: 23.0101 SSIM: 0.629250
name: 48.png  PSNR: 25.2260 SSIM: 0.669808
name: 49.png  PSNR: 18.2416 SSIM: 0.442128
name: 5.png  PSNR: 25.3566 SSIM: 0.601034
name: 50.png  PSNR: 25.2659 SSIM: 0.698263
name: 51.png  PSNR: 25.4757 SSIM: 0.809644
name: 52.png  PSNR: 28.0276 SSIM: 0.720632
name: 53.png  PSNR: 29.0710 SSIM: 0.869649
name: 54.png  PSNR: 23.4945 SSIM: 0.629087
name: 55.png  PSNR: 27.6998 SSIM: 0.699853
name: 56.png  PSNR: 24.2856 SSIM: 0.522730
name: 57.png  PSNR: 33.5004 SSIM: 0.817738
name: 58.png  PSNR: 26.5850 SSIM: 0.668816
name: 59.png  PSNR: 23.7712 SSIM: 0.555541
name: 6.png  PSNR: 25.6006 SSIM: 0.757352
name: 60.png  PSNR: 19.9321 SSIM: 0.428162
name: 61.png  PSNR: 21.0603 SSIM: 0.579966
name: 62.png  PSNR: 31.2969 SSIM: 0.790486
name: 63.png  PSNR: 29.7443 SSIM: 0.853168
name: 64.png  PSNR: 27.4760 SSIM: 0.650388
name: 65.png  PSNR: 25.7767 SSIM: 0.662686
name: 66.png  PSNR: 23.1781 SSIM: 0.624181
name: 67.png  PSNR: 23.9780 SSIM: 0.648498
name: 68.png  PSNR: 27.2769 SSIM: 0.906077
name: 69.png  PSNR: 23.2596 SSIM: 0.701108
name: 7.png  PSNR: 19.6028 SSIM: 0.324438
name: 70.png  PSNR: 24.6539 SSIM: 0.647443
name: 71.png  PSNR: 27.0315 SSIM: 0.768670
name: 72.png  PSNR: 21.8041 SSIM: 0.500889
name: 73.png  PSNR: 21.6094 SSIM: 0.533634
name: 74.png  PSNR: 27.3286 SSIM: 0.685918
name: 75.png  PSNR: 21.1609 SSIM: 0.411213
name: 76.png  PSNR: 21.3333 SSIM: 0.395431
name: 77.png  PSNR: 32.4234 SSIM: 0.914452
name: 78.png  PSNR: 26.7008 SSIM: 0.763594
name: 79.png  PSNR: 25.8549 SSIM: 0.801528
name: 8.png  PSNR: 25.0890 SSIM: 0.733869
name: 80.png  PSNR: 28.8108 SSIM: 0.821915
name: 81.png  PSNR: 24.6274 SSIM: 0.681445
name: 82.png  PSNR: 27.2558 SSIM: 0.900994
name: 83.png  PSNR: 25.0046 SSIM: 0.606474
name: 84.png  PSNR: 23.9488 SSIM: 0.581686
name: 85.png  PSNR: 22.1634 SSIM: 0.422565
name: 86.png  PSNR: 30.1194 SSIM: 0.881878
name: 87.png  PSNR: 22.7623 SSIM: 0.604833
name: 88.png  PSNR: 27.6570 SSIM: 0.820203
name: 89.png  PSNR: 24.0446 SSIM: 0.692648
name: 9.png  PSNR: 29.4758 SSIM: 0.759664
name: 90.png  PSNR: 24.5430 SSIM: 0.642925
name: 91.png  PSNR: 22.5532 SSIM: 0.615586
name: 92.png  PSNR: 23.9823 SSIM: 0.720689
name: 93.png  PSNR: 28.6490 SSIM: 0.777214
name: 94.png  PSNR: 26.9624 SSIM: 0.768835
name: 95.png  PSNR: 19.7497 SSIM: 0.367412
name: 96.png  PSNR: 29.2934 SSIM: 0.918571
name: 97.png  PSNR: 18.6745 SSIM: 0.403336
name: 98.png  PSNR: 28.9148 SSIM: 0.861889
name: 99.png  PSNR: 24.1398 SSIM: 0.762128
MEAN PSNR: 25.4320  MEAN SSIM: 0.690725
```

**Comment by House-Leo** [comment]
> I test the images of DIV2KRK using the official codes of Real-SR. The PSNR results are then calculated by codes provided in mmsr. The log file is shown below. And the reconstructed results are available at [BaiduYun](https://pan.baidu.com/s/1o3H-UJ5TgNydu_coW2OVYg)(Password:dogg)
> 
> ```shell
> name: 1.png  PSNR: 25.1982 SSIM: 0.649866
> name: 10.png  PSNR: 25.9101 SSIM: 0.693702
> name: 100.png  PSNR: 21.4348 SSIM: 0.622757
> name: 11.png  PSNR: 25.6796 SSIM: 0.608156
> name: 12.png  PSNR: 25.9424 SSIM: 0.725101
> name: 13.png  PSNR: 25.7398 SSIM: 0.762747
> name: 14.png  PSNR: 25.7414 SSIM: 0.827590
> name: 15.png  PSNR: 31.2067 SSIM: 0.878845
> name: 16.png  PSNR: 28.4497 SSIM: 0.746119
> name: 17.png  PSNR: 28.4146 SSIM: 0.802731
> name: 18.png  PSNR: 25.2095 SSIM: 0.787351
> name: 19.png  PSNR: 24.7117 SSIM: 0.613959
> name: 2.png  PSNR: 29.4142 SSIM: 0.822745
> name: 20.png  PSNR: 20.7445 SSIM: 0.580091
> name: 21.png  PSNR: 20.9119 SSIM: 0.677046
> name: 22.png  PSNR: 26.4613 SSIM: 0.706185
> name: 23.png  PSNR: 24.3018 SSIM: 0.721123
> name: 24.png  PSNR: 24.2259 SSIM: 0.781531
> name: 25.png  PSNR: 22.4599 SSIM: 0.599798
> name: 26.png  PSNR: 22.5480 SSIM: 0.625456
> name: 27.png  PSNR: 29.0917 SSIM: 0.822089
> name: 28.png  PSNR: 16.3657 SSIM: 0.600568
> name: 29.png  PSNR: 25.8496 SSIM: 0.500479
> name: 3.png  PSNR: 30.0753 SSIM: 0.916393
> name: 30.png  PSNR: 23.5194 SSIM: 0.616623
> name: 31.png  PSNR: 24.1232 SSIM: 0.679874
> name: 32.png  PSNR: 24.5258 SSIM: 0.711132
> name: 33.png  PSNR: 29.4762 SSIM: 0.873481
> name: 34.png  PSNR: 24.1261 SSIM: 0.669190
> name: 35.png  PSNR: 22.2962 SSIM: 0.426076
> name: 36.png  PSNR: 22.4708 SSIM: 0.641565
> name: 37.png  PSNR: 22.4536 SSIM: 0.612771
> name: 38.png  PSNR: 34.4451 SSIM: 0.890101
> name: 39.png  PSNR: 28.3216 SSIM: 0.765556
> name: 4.png  PSNR: 23.8126 SSIM: 0.608969
> name: 40.png  PSNR: 25.6396 SSIM: 0.665037
> name: 41.png  PSNR: 26.3366 SSIM: 0.769627
> name: 42.png  PSNR: 26.6107 SSIM: 0.750407
> name: 43.png  PSNR: 33.0029 SSIM: 0.962516
> name: 44.png  PSNR: 34.7669 SSIM: 0.975681
> name: 45.png  PSNR: 21.0279 SSIM: 0.586573
> name: 46.png  PSNR: 24.6369 SSIM: 0.764714
> name: 47.png  PSNR: 23.0101 SSIM: 0.629250
> name: 48.png  PSNR: 25.2260 SSIM: 0.669808
> name: 49.png  PSNR: 18.2416 SSIM: 0.442128
> name: 5.png  PSNR: 25.3566 SSIM: 0.601034
> name: 50.png  PSNR: 25.2659 SSIM: 0.698263
> name: 51.png  PSNR: 25.4757 SSIM: 0.809644
> name: 52.png  PSNR: 28.0276 SSIM: 0.720632
> name: 53.png  PSNR: 29.0710 SSIM: 0.869649
> name: 54.png  PSNR: 23.4945 SSIM: 0.629087
> name: 55.png  PSNR: 27.6998 SSIM: 0.699853
> name: 56.png  PSNR: 24.2856 SSIM: 0.522730
> name: 57.png  PSNR: 33.5004 SSIM: 0.817738
> name: 58.png  PSNR: 26.5850 SSIM: 0.668816
> name: 59.png  PSNR: 23.7712 SSIM: 0.555541
> name: 6.png  PSNR: 25.6006 SSIM: 0.757352
> name: 60.png  PSNR: 19.9321 SSIM: 0.428162
> name: 61.png  PSNR: 21.0603 SSIM: 0.579966
> name: 62.png  PSNR: 31.2969 SSIM: 0.790486
> name: 63.png  PSNR: 29.7443 SSIM: 0.853168
> name: 64.png  PSNR: 27.4760 SSIM: 0.650388
> name: 65.png  PSNR: 25.7767 SSIM: 0.662686
> name: 66.png  PSNR: 23.1781 SSIM: 0.624181
> name: 67.png  PSNR: 23.9780 SSIM: 0.648498
> name: 68.png  PSNR: 27.2769 SSIM: 0.906077
> name: 69.png  PSNR: 23.2596 SSIM: 0.701108
> name: 7.png  PSNR: 19.6028 SSIM: 0.324438
> name: 70.png  PSNR: 24.6539 SSIM: 0.647443
> name: 71.png  PSNR: 27.0315 SSIM: 0.768670
> name: 72.png  PSNR: 21.8041 SSIM: 0.500889
> name: 73.png  PSNR: 21.6094 SSIM: 0.533634
> name: 74.png  PSNR: 27.3286 SSIM: 0.685918
> name: 75.png  PSNR: 21.1609 SSIM: 0.411213
> name: 76.png  PSNR: 21.3333 SSIM: 0.395431
> name: 77.png  PSNR: 32.4234 SSIM: 0.914452
> name: 78.png  PSNR: 26.7008 SSIM: 0.763594
> name: 79.png  PSNR: 25.8549 SSIM: 0.801528
> name: 8.png  PSNR: 25.0890 SSIM: 0.733869
> name: 80.png  PSNR: 28.8108 SSIM: 0.821915
> name: 81.png  PSNR: 24.6274 SSIM: 0.681445
> name: 82.png  PSNR: 27.2558 SSIM: 0.900994
> name: 83.png  PSNR: 25.0046 SSIM: 0.606474
> name: 84.png  PSNR: 23.9488 SSIM: 0.581686
> name: 85.png  PSNR: 22.1634 SSIM: 0.422565
> name: 86.png  PSNR: 30.1194 SSIM: 0.881878
> name: 87.png  PSNR: 22.7623 SSIM: 0.604833
> name: 88.png  PSNR: 27.6570 SSIM: 0.820203
> name: 89.png  PSNR: 24.0446 SSIM: 0.692648
> name: 9.png  PSNR: 29.4758 SSIM: 0.759664
> name: 90.png  PSNR: 24.5430 SSIM: 0.642925
> name: 91.png  PSNR: 22.5532 SSIM: 0.615586
> name: 92.png  PSNR: 23.9823 SSIM: 0.720689
> name: 93.png  PSNR: 28.6490 SSIM: 0.777214
> name: 94.png  PSNR: 26.9624 SSIM: 0.768835
> name: 95.png  PSNR: 19.7497 SSIM: 0.367412
> name: 96.png  PSNR: 29.2934 SSIM: 0.918571
> name: 97.png  PSNR: 18.6745 SSIM: 0.403336
> name: 98.png  PSNR: 28.9148 SSIM: 0.861889
> name: 99.png  PSNR: 24.1398 SSIM: 0.762128
> MEAN PSNR: 25.4320  MEAN SSIM: 0.690725
> ```

Thanks for your answer.
