### ISSUE TITLE
The SSIM is much lower

### ISSUE THREAD

**Issue by zejinwang** [greatlog/DAN#15]
I have generated the test dataset according to the test setting1 and test the provided pre-trained model on it. The PNSR results are roughly the same as you have mentioned in Table 1. However, the SSIM is much lower.  Could tell me how to solve this issue.

**Comment by greatlog** [comment]
It seems to be a bug in the older version of [IKC](!https://github.com/yuanjunchai/IKC.git). The reported SSIM results of IKC and our models on Setting 1 are wrong. Probably the SSIM results in Table 1 are all wrong. While the authors of IKC do not provide any explanation, I will correct these results according to my re-implementation.

**Comment by zejinwang** [comment]
> It seems to be a bug in the older version of [IKC](https://github.com/yuanjunchai/IKC.git). The reported SSIM results of IKC and our models on Setting 1 are wrong. Probably the SSIM results in Table 1 are all wrong. While the authors of IKC do not provide any explanations, I will correct these results according to my re-implementation. The corrected results will de updated soon.

Thanks for your quick and detailed reply. I got it.
