### ISSUE TITLE
Wrong pth file?

### ISSUE THREAD

**Issue by zhihongp** [greatlog/DAN#17]
It seems pca_aniso_matrix_x4.pth and pca_matrix.pth are identical, while one is anisotropic and the other isotropic.  Please check

**Comment by greatlog** [comment]
It seems that we have made a mistake about the pca_matrix when training DANv1 under setting 1 for scale x4. Actually, we have tested the same model for both setting 1 and setting 2. The results suggest that models trained under setting 1 are also able to generalize to setting 2.
