### ISSUE TITLE
How can I get the same SSIM results?

### ISSUE THREAD

**Issue by Arcananana** [greatlog/DAN#18]
Hi, I noticed that due to some bugs in the older version of IKC, I can't get the same SSIM results in Table 1. Could you please provide the codes about calculating  SSIM results in Table 1? I can't find a version of IKC which provides the same SSIM results as in their paper. Thank you!

**Comment by greatlog** [comment]
We fix the bugs and revise the results of IKC and DAN as below:

| Method | Scale |   Set5  |          |  Set14  |          |   B100  |          | Urban100 |          | Mangan109 |          |
|:------:|:-----:|:-------:|:--------:|:-------:|:--------:|:-------:|:--------:|:--------:|:--------:|:---------:|:--------:|
|   IKC  |   x2  | $37.19$ | $0.9526$ | $32.94$ | $0.9024$ | $31.51$ | $0.8790$ |  $29.85$ | $0.8928$ |  $36.93$  | $0.9667$ |
|   DAN  |       | $37.34$ | $0.9526$ | $33.08$ | $0.9041$ | $31.76$ | $0.8858$ |  $30.60$ | $0.9060$ |  $37.23$  | $0.9710$ |
|   IKC  |   x3  | $33.06$ | $0.9146$ | $29.38$ | $0.8233$ | $28.53$ | $0.7899$ |  $27.43$ | $0.8302$ |  $32.43$  | $0.9316$ |
|   DAN  |       | $34.04$ | $0.9199$ | $30.09$ | $0.8287$ | $28.94$ | $0.7919$ |  $27.65$ | $0.8352$ |  $33.16$  | $0.93824 |
|   IKC  |   x4  | $31.67$ | $0.8829$ | $28.31$ | $0.7643$ | $27.37$ | $0.7192$ |  $25.33$ | $0.7504$ |  $28.91$  | $0.8782$ |
|   DAN  |       | $31.89$ | $0.8864$ | $28.42$ | $0.7687$ | $27.51$ | $0.7248$ |  $25.86$ | $0.7721$ |   $30.50$ | $0.9037$ |

**Comment by Arcananana** [comment]
Thanks for your reply.
