### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by splinter21** [greatlog/DAN#2]
RuntimeError: ../../../checkpoints/DANx4.pth is a zip archive (did you mean to use torch.jit.load()?)

/DAN-master/codes/config/DAN/models/base_model.py", line 96, in load_network
    load_net = torch.load(load_path)

**Comment by greatlog** [comment]
How do you download the checkpoints? I re-download these files and they can be loaded successfully on my computer.

**Comment by splinter21** [comment]
![111](https://user-images.githubusercontent.com/26759495/95650862-f7d53d80-0b18-11eb-9d56-ad4ed35e5340.png)
![222](https://user-images.githubusercontent.com/26759495/95650881-189d9300-0b19-11eb-98ff-641c68852604.png)

I downloaded DANx4.pth from BaiduDrive. And it can be unziped. (to unzip it on windows I change the suffix to .zip)

**Comment by KevinJ-Huang** [comment]
The same problem, have you solved it?

**Comment by 953250587** [comment]
pytorch 1.6.0 can work
