### ISSUE TITLE
请问测试集是怎么生成的

### ISSUE THREAD

**Issue by Fangzhenxuan** [greatlog/DAN#21]
您好，对于X2的SR，请问怎么生成Gaussian8的kernel，Set5的每张测试图片都需要生成8张不同的LR图片吗

**Comment by greatlog** [comment]
是的，对Setting1，每张图都需要生成8张不同的LR，分别对应8个不同Gaussian Kernel. 对x4来说，kerne的标准差在[0.2, 4.0]等间隔取8个，x3在[0.2, 3.0]等间隔取8个, x2在[0.2, 2.0]等间隔取8个。

**Comment by Fangzhenxuan** [comment]
非常感谢您的回复，但是您说的范围是training的吧。对于testing，x4来说，kerne的标准差应该在[1.8, 3.2]等间隔取8个，x3在[1.35, 2.40]等间隔取8个, x2在[0.80, 1.60]等间隔取8个，
‘’ we uniformly choose 8 kernels, denoted as Gaussian8, from range [1.8, 3.2], [1.35, 2.40] and [0.80, 1.60] for scale factors 4, 3 and 2 respectively‘’
