### ISSUE TITLE
About testing on real image.

### ISSUE THREAD

**Issue by MeLonJ10** [greatlog/DAN#23]
Hi, it's definitely a fantastic work.
About testing on real image, I am confused.
According to your paper, the SR model inferencing on real image is trained with AWGN. However, in codes/config/DANv1/inference.py, SR model is the same with that of setting1. 
I also tested it (with inference.py) on image captured by my own device. The result is quite blur.
Is there any misunderstanding.
Thanks a lot.

**Comment by greatlog** [comment]
In fact, super-resolution on real images is a quite challenging task. The provided test images may consist of noise, blurring, JEPG compressing defects, and so on. The provided model considers only noise and uniform blurring, which may still leave to be desired in practice. It may work in some cases but is likely to fail on an image randomly downloaded from the website.

Actually, The test image 'chip' is relatively clean and consists of little noise. Thus the model trained on Setting 1 is good enough to produce a visually pleasing result on this image. 

There is still a long way to go for practical SR.

**Comment by MeLonJ10** [comment]
I agree with your opinion about realistic super-resolution.
In a deep alternating network, there are several restorers to super-resolve the input LR image. Do the restorers share the same weight?
Thanks!

**Comment by greatlog** [comment]
Yes, the Restorer and Estimator share their weights among all iterations.

**Comment by CodeMadUser** [comment]
> Hi, it's definitely a fantastic work. About testing on real image, I am confused. According to your paper, the SR model inferencing on real image is trained with AWGN. However, in codes/config/DANv1/inference.py, SR model is the same with that of setting1. I also tested it (with inference.py) on image captured by my own device. The result is quite blur. Is there any misunderstanding. Thanks a lot.

hello, I couldn't save the test results when I was testing the real image, I don't know what went wrong, hope to get a reply. thank you.
![image](https://user-images.githubusercontent.com/97572749/208081366-6b6a2b4b-dc87-43ef-9222-a61c02ae8267.png)
No result is produced after the execution of the code. Do you have any suggestions?
![image](https://user-images.githubusercontent.com/97572749/208081558-2554327a-752d-4350-9aaa-7309173fc9ea.png)
