### ISSUE TITLE
Run without external GPU?

### ISSUE THREAD

**Issue by SB2020-eye** [greatlog/DAN#24]
Hi.

Is there any way to run this if I don't have an external GPU?

(I just have an integrated graphics card.)

Thanks.

**Comment by greatlog** [comment]
I am afraid that it is impossible to run this code without a GPU. Sorry for that. 

( I've heard that f you are a student, you may be able to apply for a free Amazon for Google server. I'm not sure about it. Maybe you can have a try.)
