### ISSUE TITLE
'OrderedYaml' is not defined

### ISSUE THREAD

**Issue by ontheway16** [greatlog/DAN#26]
I am having the following error;
```
~/DAN/codes/config/DANv1$ python3 test.py -opt=options/setting1/test_setting1_x4.yml
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    import options as option
  File "/home/alper/DAN/codes/config/DANv1/options.py", line 14, in <module>
    Loader, Dumper = OrderedYaml()
NameError: name 'OrderedYaml' is not defined
```

**Comment by wileechou** [comment]
You may change options.py file from
'
try:
    sys.path.append("../../")
    from utils import OrderedYaml
except ImportError:
    pass
'

to 

'
sys.path.append("../../")
from utils import OrderedYaml
'
You will get more details about error in this way, such as some packages are uninstalled.

**Comment by alexgg94** [comment]
I have the same issue. Im my case, after importing it without try-catch, I'm getting **ImportError: cannot import name 'OrderedYaml' from 'utils' (C:\Users\ag\Miniconda3\envs\tf\lib\site-packages\utils\__init__.py)**.
