### ISSUE TITLE
About the dataset preparation

### ISSUE THREAD

**Issue by yuzheyyyy** [greatlog/DAN#27]
Hi, I would like to ask a question about the dataset preparation. I find that in 'train.py', the 'blur_lr_imgs' are generated online, that is to say, they are generated during training process. For those 'blur_lr_img' generated offline, they are only used in validating process. Does that mean I should only run 'python3 codes/scripts/generate_mod_blur_LR_bic.py' for validation dataset not for train dataset? I think it's not clarified very well in this repo.

**Comment by greatlog** [comment]
yes, the validation datasets are generated offline, while the training dataset is generated on the fly.

**Comment by AmirMohamadBabaee** [comment]
Hello, thank you for the amazing repository. 
I was reading the [dataset preparation](https://github.com/greatlog/DAN#dataset-preparation) section of the `README.md` file and at first glance, it seems that both the training and validation datasets should be generated offline. I was wondering if it would be possible to add a note to the `README.md` file clarifying this point. Thank you again.
