### ISSUE TITLE
kernel size of setting2

### ISSUE THREAD

**Issue by powder21** [greatlog/DAN#28]
I'm interested in the great work. But I found the size of blur kernel is not consistent in DANv1 and v2 for setting2 scale 4.
In DANv1 and kernelGAN, the kernel size is 11.
In DANv2, it is 31.
The quantitative results in the paper of DANv2 is the same as those in DANv1 paper except the additional DANv2, which means testing of DANv2 is the same as DANv1. So you train DANv2 with data blurred by kernel 31 and test it with data blurred by kernel 11. Is there something wrong in my understanding?

**Comment by greatlog** [comment]
Both DANv1 and DANv2 set kernel size as 31 for x4 on DIV2KRK.

According to the provided kernels in DIV2KRK, the kernel size is 11 for x2 and 31 for x4. The paper of KernelGAN actually only describes the case of x2.

**Comment by powder21** [comment]
I see. But why the kernel size of DAN/pca_matrix/DANv1/pca_aniso_matrix_x4.pth is 21, where as DAN/pca_matrix/DANv2/pca_aniso_matrix_x4.pth is 31.

**Comment by greatlog** [comment]
It is a mistake. The pca_aniso_matrix_x4.pth in DANv1 is actually the same as its pca_matrix.pth. And the model is trained and tested with this matrix. In fact, if you replace it with a correct matrix, DANv1 should be able to achieve better results.

**Comment by powder21** [comment]
Thx a lot!
