### ISSUE TITLE
About the  'kernel_code'? 

### ISSUE THREAD

**Issue by yiyunchen** [greatlog/DAN#29]
hello,
I am confused about the generation process of 'kernel_code'.
When calculating the PCA matrix, the code do 'X = X - X_mean.expand_as(X)' before get the PCA matrix.
Then, in 'PCAEncoder', It seems direct projection by 'torch.bmm(
            batch_kernel.view((B, 1, H * W)), self.weight.expand((B,) + self.size)
        ).view((B, -1))' without '- X_mean'.
Did we need '- X_mean'?

Thank you!

**Comment by greatlog** [comment]
Strictly speaking, we do need ' - x_mean' to properly encode the kernel. However, our experiments show that it is ok to omit this step. In option, you may get slightly better results if you add ' - x_mean' back.
