### ISSUE TITLE
Error of testing

### ISSUE THREAD

**Issue by jiandandan001** [greatlog/DAN#3]
Hi, thank you for this excellent work and thank you for sharing the code.

I have the following problem when runing  the testing code as : 
python test_single_img.py -opt=test_option.yml -input_dir=D:/2020/ReferenceCode/DAN-master/our_testimages/ -output_dir=D:/2020/ReferenceCode/DAN-master/our_results/

The environment is:  python 3.7 / torch 1.6

Could you please give me some suggestions to slove this problem? Thanks

***************************
G:\Anaconda\envs\py3.7to1.6\python.exe D:/2020/ReferenceCode/DAN-master/codes/config/DAN/test_single_img.py
export CUDA_VISIBLE_DEVICES=0
OrderedDict([('name', 'DIV2KRK'), ('mode', 'LQGTker'), ('dataroot_GT', '/data/DIV2KRK_public/HRblur.lmdb'), ('dataroot_LQ', '/data/DIV2KRK_public/x2LRblur.lmdb')])
Traceback (most recent call last):
  File "D:/2020/ReferenceCode/DAN-master/codes/config/DAN/test_single_img.py", line 32, in <module>
    opt = option.parse(args.opt, is_train=False)
  File "D:\2020\ReferenceCode\DAN-master\codes\config\DAN\options.py", line 56, in parse
    config_dir = path.split("/")[-3]  
IndexError: list index out of range

Process finished with exit code 1
********************************************

**Comment by greatlog** [comment]
It seems that the path on windows could not be written like that. Maybe you can modify the directory path in test_single_img.py directly,  instead of passing them via argument parser.
