### ISSUE TITLE
about the setting of  the kernel width？

### ISSUE THREAD

**Issue by ScarletBlaze** [greatlog/DAN#32]
Thank you for sharing. I learned a lot from your paper, but I still have a question about the kernel settings. Does the kernel width and its standard deviation mean the same thing? In your paper you mentioned that "During training, the kernel width is uniformly sampled in [0.2, 4.0], [0.2, 3.0] and [0.2, 2.0] for scale factors 4 , 3 and 2 respectively", but I found in your code that the kernels sigma are all set to [0.2, 4.0] for different upsampling rates, so do I need to change this part when retraining if I want to keep the same settings as in your original paper? Thank you very much!

**Comment by greatlog** [comment]
Yes, the kernel width is also the standard deviation.

**Comment by wwlCape** [comment]
@ScarletBlaze Hi, can you get similar results with the original paper when retraining in setting1_x2?
