### ISSUE TITLE
作者您好，运行generate_mod_blur_LR_bic.py 时

### ISSUE THREAD

**Issue by chenlanzheng** [greatlog/DAN#34]
![微信图片_20210913223546](https://user-images.githubusercontent.com/35997309/133103360-a2eab0e8-9415-484b-b908-4e9548f5136b.jpg)
请问作者您有遇到这种情况吗？一开始报错找不到pca_matrix.pth路径，我在generate_mod_blur_LR_bic.py里修改路径（../../pca_matrix/DANv1/pca_matrix.pth）之后出现如图的报错。

**Comment by greatlog** [comment]
这个报错是数据路径写错了，你给的数据路径里没有图片
