### ISSUE TITLE
About methods comparison

### ISSUE THREAD

**Issue by LBJ23233** [greatlog/DAN#37]
Thanks for your nice work!
I am a beginner in blind sr, so I do not understand why methods like EDSR are **trained under the bicubic** downsampling setting while **tested under the multiple-degradation setting**.
Looking forward to your reply！

**Comment by greatlog** [comment]
We reuse the statics of IKC and KernelGAN. In fact, for a fair comparison, all methods should be retrained under the same setting.

**Comment by LBJ23233** [comment]
> We reuse the statics of IKC and KernelGAN. In fact, for a fair comparison, all methods should be retrained under the same setting.

Did you have ever retrain those methods? Maybe end2end methods (such as EDSR) are better under the same setting?
As far as I know,  none of the existing blind sr methods are compared with them under the same settings

**Comment by greatlog** [comment]
Some recent works have studied this problem. This [paper](https://arxiv.org/abs/2108.01070) has demonstrated that a simple end-to-end network can also achieve competitive performance.
