### ISSUE TITLE
Results when not using blur kernel

### ISSUE THREAD

**Issue by samtwiappayaic** [greatlog/DAN#38]
Hello, and thanks for making the code available!
I am curious as to what the SR results are when not using the blur kernel during the SR process (for ex., only inputting a delta kernel as the conditional input for the Restorer during the training process). Of course, in this case it won't be possible to estimate the blur kernel. 
If you have checked the SR results when not using the blur kernel, it would be great if you could share them!

**Comment by greatlog** [comment]
You can refer to Section 4.1.4 in our paper. When iter=1, it is exactly the case where there is only a deal kernel.
