### ISSUE TITLE
关于setting2下的训练和测试问题

### ISSUE THREAD

**Issue by leeziqiang** [greatlog/DAN#41]
你好，想问下setting2中train和test的yaml配置中input_pare=15,而在setting1中用10？

**Comment by greatlog** [comment]
setting2中的kernel相对更复杂，属于anisotropic, 我们推测需要更长的向量来进行编码。

**Comment by wwlCape** [comment]
@leeziqiang 朋友你训练x2的时候会出现不收敛的问题么？

**Comment by leeziqiang** [comment]
这倒没有

**Comment by wwlCape** [comment]
朋友，方便加一下您联系方式么，我训练2倍的时候，训练一段时间会出现psnr徘徊在7db的情况，这个问题困扰我很久，想跟您请教一下，十分感谢！我的微信 q2684833523 谢谢！发自我的荣耀手机-------- 原始邮件 --------发件人： Ziqiang Li ***@***.***>日期： 2022年4月11日周一 13:52收件人： greatlog/DAN ***@***.***>抄送： 五维 ***@***.***>, Comment ***@***.***>主    题： Re: [greatlog/DAN] 关于setting2下的训练和测试问题 (Issue #41)

这倒没有

**Comment by wwlCape** [comment]
朋友，方便加一下您联系方式么，我训练2倍的时候，训练一段时间会出现psnr徘徊在7db的情况，这个问题困扰我很久，想跟您请教一下，十分感谢！我的微信 q2684833523 谢谢！

**Comment by wwlCape** [comment]
@leeziqiang 朋友，方便加一下您联系方式么，我训练2倍的时候，训练一段时间会出现psnr徘徊在7db的情况，这个问题困扰我很久，想跟您请教一下，十分感谢！我的微信 q2684833523 谢谢！

**Comment by para999** [comment]
> @leeziqiang 朋友你训练x2的时候会出现不收敛的问题么？

有，请问您知道有解决途径吗
