### ISSUE TITLE
can't find results

### ISSUE THREAD

**Issue by CodeMadUser** [greatlog/DAN#45]
Hello, DAN is an amazing framework, but I couldn't save the test results when I was testing the real image, I don't know what went wrong, hope to get a reply. thank you.

![image](https://user-images.githubusercontent.com/97572749/208072531-e130b08e-ca8e-4f59-a055-cc5f3af4b981.png)
![image](https://user-images.githubusercontent.com/97572749/208072677-58128e0f-21e9-4ba9-a20b-0bc93f8038ad.png)

**Comment by Sheeran2000** [comment]
Hey bro, have you solved this problem yet?
