### ISSUE TITLE
关于LQGT

### ISSUE THREAD

**Issue by LI945** [greatlog/DAN#5]
你好，谢谢你很有意义的工作和代码。但是我有一个问题就是提供的代码中，yaml的训练数据的模式是LQGTKer，但是训练中却是将GT模糊下采样后得到LR_img, ker_map并用他们训练。dataloader中的LQ数据并没有被使用且没有ker_map的lmdb。这样做是为了增加模糊核的随机性么？将LQ GT 和模糊核都做成lmdb而不是在训练的时候生成会不会降低性能，减少训练时间？

**Comment by greatlog** [comment]
我们的kernel是在线生成的，这个过程经过并行优化还是比较快的。如果把训练数据预先存下来，会导致kernel的多样性不足，而且会占用很多硬盘空间。
