### ISSUE TITLE
How can I only get output from a custom image?

### ISSUE THREAD

**Issue by koreadhkim** [greatlog/DAN#6]
How can I only get output from a custom image?

**Comment by koreadhkim** [comment]
Additionally, the below seems to be wrong.

test_single_image.py

![image](https://user-images.githubusercontent.com/48986889/96740255-9f951a00-13fb-11eb-9c22-4bd672098056.png)

**Comment by greatlog** [comment]
You can use the following command.
```bash
cd codes/config/DAN
python3 test_single_image.py -opt=test_option.yml -input_dir=/path/to/real/images/ -output_dir=/path/to/save/sr/results/
```
Remember to change the paths properly.
