### ISSUE TITLE
Problem of loss ‘NAN’ value during training

### ISSUE THREAD

**Issue by LBJ23233** [greatlog/DAN#8]
Thanks for your work so much.
Like the title, I meet the error that loss value is NAN at 22800 iterations (Second time: 29200) suddenly. 
Did you have ever met this kind of error?

**Comment by greatlog** [comment]
Yes, this situation occurs sometimes. A workaround method is to resume from the last normal training state.

**Comment by LBJ23233** [comment]
> Yes, this situation occurs sometimes. A workaround method is to resume from the last normal training state.

Thanks, it is how I solve this mistake

**Comment by greatlog** [comment]
Sorry, I have not figured it out yet. If you have any ideas please tell me. Thank you.

**Comment by LBJ23233** [comment]
> Sorry, I have not figured it out yet. If you have any ideas please tell me. Thank you.

I don't find the key, too. In the last 20 hours, this error has occurred several times, when the num of iterations over 115000 especially. Is it common?

**Comment by greatlog** [comment]
In my case, it occurs twice during 400000 iterations. The frequency seems to be random. Maybe it is an inherent drawback of the proposed method, as DAN is actually a recurrent neural network (RNN). Maybe  I can borrow some ideas from RNNs to stabilize the training.

**Comment by LBJ23233** [comment]
> In my case, it occurs twice during 400000 iterations. The frequency seems to be random. Maybe it is an inherent drawback of the proposed method, as DAN is actually a recurrent neural network (RNN). Maybe I can borrow some ideas from RNNs to stabilize the training.
OK，thanks for your reply
